### A Nbdev script file ###
### Autogenerated file. Don't modify. ###

module Common
#export
using TOML

#export
begin
function getsetting(f:: AbstractString, k:: AbstractString)
	a = TOML.parsefile(f)
	return a[k]
end

function getsettings(f:: AbstractString, ks)
	res = TOML.parsefile(f)
	for k in ks
		#"$res"
		res = res[k]
	end
	return res
end
end

end